### ISSUE TITLE
Latest commit causing server response error code 404

### ISSUE THREAD

**Issue by sollarp** [lambiengcode/compose-chatgpt-kotlin-android-chatbot#11]
Hi Kai,

I have noticed your latest commit causing server response error must be the issue with the request format. Can you confirm this? 

![response error](https://github.com/lambiengcode/compose-chatgpt-kotlin-android-chatbot/assets/74240451/44be38d3-62cf-4d81-bd0b-12901fdfa1c7)

**Comment by lambiengcode** [comment]
Thanks for report, gpt 4 needs to be licensed from OpenAI, if your api_key is not approved then use gpt3 instead of gpt4

**Comment by sollarp** [comment]
That must the issue. Unfortunately I do not have a gpt4 license but the gpt3 key does not work with the latest commit out of the box.

**Comment by lambiengcode** [comment]
okay, I'm fix it in [commit](af64b7f0cf913052b1edadf61c4919855b60a102), let check it!

**Comment by sollarp** [comment]
Sorry for being a pain .I have tested you latest commit but the issue remained. I can confirm the API has been called at server side but the response not been handled properly. Have you tested this with gpt3 only key? Thanks
