### ISSUE TITLE
Need Settings for inserting chatGPT api key

### ISSUE THREAD

**Issue by x-0D** [lambiengcode/compose-chatgpt-kotlin-android-chatbot#2]
App just crashes if i try to talk. I think it is because chatGPT api key is missing. Where i can set up my key?

**Comment by lambiengcode** [comment]
@x-0D 
1. you need create firebase project and setup firestore
2. download ***google-services.json*** and put it in to /app
3. generate api key from openai console: https://platform.openai.com/account/api-keys
4. in the app/src/main/java/com/chatgptlite/wanted/constants/Constants.kt file, replace with your actual API key: openAIApiKey=<api_key_here>

**Comment by lambiengcode** [comment]
@x-0D i just uploaded the google-services.json file, you just need to change your openai_api_key to run the project.
