### ISSUE TITLE
App crashes when you delete any of your chat history 

### ISSUE THREAD

**Issue by 4niso** [lambiengcode/compose-chatgpt-kotlin-android-chatbot#21]
The app works fine but once you go to the menu and click the delete icon to delete any of your chat history, the app crashes. You will then have to run the app again. when the app is back, when you check, you will see that the chat history you tried to delete is still there.

This was noticed on android studio emulator, I have not tried it on a phone to see how this playout.

Please how can this be fix. 

Thanks

**Comment by lambiengcode** [comment]
Please help me check it again in latest code.

**Comment by 4niso** [comment]
Ok Boss, I will check it again and let you know as soon as possible. Thank
you for taking your time to look into the code again I appreciate.

Akpaniwo Godfrey M.

:::::> *PUBLICATIONS*<::::::
Google scholar: https://scholar.google.com/citations?hl=en&user=lrx9UcAAAAAJ
Research gate: https://www.researchgate.net/profile/Akpaniwo_Gm

**Comment by 4niso** [comment]
The code is working perfectly now, I have tested it again and again, I deleted several old chats and the app did not crash. Thank you so much for fixing the code. I appreciate
