### ISSUE TITLE
Unable to change markdown's text color | unable to see text from ChatGPT

### ISSUE THREAD

**Issue by wingsum93** [lambiengcode/compose-chatgpt-kotlin-android-chatbot#5]
<img width="503" alt="圖片" src="https://user-images.githubusercontent.com/13871554/233659717-6afc43f8-8dd3-4b5e-9103-447be54683b1.png">

This issue happen when i use **light** theme in my phone.

I found it unable to change the text color of Markdown component. The only possible solution is to change the "BackGroundMessageGPT" to other color.

**Comment by wingsum93** [comment]
<img width="511" alt="圖片" src="https://user-images.githubusercontent.com/13871554/233666896-747b629e-bc8e-4c36-b98e-822556e888ca.png">
When i tried other question related to code answer.

**Comment by Near707** [comment]
I present you another possible solution, in the path "java/com/chatgptlite/wanted/ui/common/AppDrawer.kt"
An 'IconButton' is defined with a sun icon (WbSunny) inside it. When the button is clicked, currently no action is executed as the 'onClick' block is empty. To add functionality to the button, you can add code inside this onClick block.

Assuming you want to switch the app theme between light and dark when you click this button, you can do the following as an example:

**Comment by Near707** [comment]
### Create a ViewModel to handle the state of the theme:

[Viewmodel.txt](https://github.com/lambiengcode/compose-chatgpt-kotlin-android-chatbot/files/11297369/Viewmodel.txt)

**Comment by Near707** [comment]
In your 'MainActivity.kt', use the 'ThemeViewModel' to change the theme based on the 'isDarkTheme' value and in your 'AppDrawer.kt' file, use the 'ThemeViewModel' to update the theme's state when clicking the button

**Comment by wingsum93** [comment]
@Near707 I do not agree your approach as it is not need to write so many code to to only 1 thing.

Instead try to use local variable in compose (mutable state - boolean)

**Comment by lambiengcode** [comment]
Contributions are welcome! @wingsum93  and @Near707, this repo doesn't get much attention so I don't have the motivation to develop it further 😢...Hope it useful for you

**Comment by wingsum93** [comment]
> Contributions are welcome! @wingsum93 and @Near707, this repo doesn't get much attention so I don't have the motivation to develop it further 😢...Hope it useful for you

There are 2 selling points for this project comparing to other android chatGPT project:
- use jetpack compose and well organized code structure
- the chatGPT respond is scrolling, while other app just return whole response and do not use buffer reader

So i think this project is useful for people who may want to develop chatGPT client
@lambiengcode  @Near707

**Comment by lambiengcode** [comment]
@wingsum93  Glad to hear about that 😄. This is my first project using Jetpack Compose. I use this project for learning and practice Compose.
